/* Generated by Yosys 0.58 (git sha1 157aabb58, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module Comb(in_num0, in_num1, in_num2, in_num3, out_num0, out_num1);
  input [6:0] in_num0;
  wire [6:0] in_num0;
  input [6:0] in_num1;
  wire [6:0] in_num1;
  input [6:0] in_num2;
  wire [6:0] in_num2;
  input [6:0] in_num3;
  wire [6:0] in_num3;
  output [7:0] out_num0;
  wire [7:0] out_num0;
  output [7:0] out_num1;
  wire [7:0] out_num1;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire [7:0] adder_result;
  sky130_fd_sc_hd__xor2_1 _171_ (
    .A(in_num1[0]),
    .B(in_num0[0]),
    .X(_116_)
  );
  sky130_fd_sc_hd__nor3_1 _172_ (
    .A(in_num0[6]),
    .B(in_num1[6]),
    .C(in_num3[6]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__or3_1 _173_ (
    .A(in_num0[6]),
    .B(in_num1[6]),
    .C(in_num3[6]),
    .X(_118_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _174_ (
    .A(in_num1[5]),
    .SLEEP(in_num3[5]),
    .X(_119_)
  );
  sky130_fd_sc_hd__o32ai_1 _175_ (
    .A1(in_num1[4]),
    .A2(in_num3[4]),
    .A3(in_num0[4]),
    .B1(in_num0[5]),
    .B2(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__clkinv_1 _176_ (
    .A(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _177_ (
    .A(in_num1[3]),
    .B(in_num3[3]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _178_ (
    .A(in_num1[3]),
    .B(in_num0[3]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor2_1 _179_ (
    .A(in_num1[2]),
    .B(in_num3[2]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _180_ (
    .A(in_num1[2]),
    .SLEEP(in_num3[2]),
    .X(_125_)
  );
  sky130_fd_sc_hd__xor2_1 _181_ (
    .A(in_num1[2]),
    .B(in_num0[2]),
    .X(_126_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _182_ (
    .A1_N(_125_),
    .A2_N(_126_),
    .B1(_122_),
    .B2(_123_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _183_ (
    .A(in_num1[1]),
    .SLEEP(in_num3[1]),
    .X(_128_)
  );
  sky130_fd_sc_hd__or3_1 _184_ (
    .A(in_num1[1]),
    .B(in_num3[1]),
    .C(in_num0[1]),
    .X(_129_)
  );
  sky130_fd_sc_hd__xor2_1 _185_ (
    .A(in_num1[1]),
    .B(in_num0[1]),
    .X(_130_)
  );
  sky130_fd_sc_hd__a21boi_0 _186_ (
    .A1(_128_),
    .A2(_130_),
    .B1_N(_129_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _187_ (
    .A(in_num1[0]),
    .B(in_num3[0]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _188_ (
    .A(_116_),
    .SLEEP(_132_),
    .X(_133_)
  );
  sky130_fd_sc_hd__o32ai_1 _189_ (
    .A1(in_num1[3]),
    .A2(in_num3[3]),
    .A3(in_num0[3]),
    .B1(_125_),
    .B2(in_num0[2]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nor4b_1 _190_ (
    .A(_127_),
    .B(_133_),
    .C(_134_),
    .D_N(_131_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a21oi_1 _191_ (
    .A1(_125_),
    .A2(_126_),
    .B1(_129_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__o22a_1 _192_ (
    .A1(_122_),
    .A2(_123_),
    .B1(_134_),
    .B2(_136_),
    .X(_137_)
  );
  sky130_fd_sc_hd__xor2_1 _193_ (
    .A(in_num1[4]),
    .B(in_num0[4]),
    .X(_138_)
  );
  sky130_fd_sc_hd__o21ai_0 _194_ (
    .A1(in_num1[4]),
    .A2(in_num3[4]),
    .B1(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o21ai_0 _195_ (
    .A1(_135_),
    .A2(_137_),
    .B1(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor3b_1 _196_ (
    .A(in_num1[6]),
    .B(in_num3[6]),
    .C_N(in_num0[6]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor3b_1 _197_ (
    .A(in_num0[6]),
    .B(in_num1[6]),
    .C_N(in_num3[6]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _198_ (
    .A1(in_num0[6]),
    .A2(in_num1[6]),
    .B1(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2b_1 _199_ (
    .A_N(_141_),
    .B(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__xor2_1 _200_ (
    .A(in_num1[5]),
    .B(in_num0[5]),
    .X(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(_119_),
    .B(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _202_ (
    .A(_144_),
    .B(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a21oi_1 _203_ (
    .A1(_121_),
    .A2(_140_),
    .B1(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a21o_1 _204_ (
    .A1(_121_),
    .A2(_140_),
    .B1(_147_),
    .X(_149_)
  );
  sky130_fd_sc_hd__or3_1 _205_ (
    .A(in_num1[0]),
    .B(in_num3[0]),
    .C(in_num0[0]),
    .X(_150_)
  );
  sky130_fd_sc_hd__and4b_1 _206_ (
    .A_N(_120_),
    .B(_139_),
    .C(_146_),
    .D(_150_),
    .X(_151_)
  );
  sky130_fd_sc_hd__nand3_1 _207_ (
    .A(_135_),
    .B(_144_),
    .C(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__clkinv_1 _208_ (
    .A(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a21oi_1 _209_ (
    .A1(_118_),
    .A2(_149_),
    .B1(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__o21ai_0 _210_ (
    .A1(_117_),
    .A2(_148_),
    .B1(_152_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a2111oi_0 _211_ (
    .A1(_118_),
    .A2(_149_),
    .B1(_153_),
    .C1(in_num3[0]),
    .D1(in_num1[0]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__and2_0 _212_ (
    .A(_116_),
    .B(_155_),
    .X(_157_)
  );
  sky130_fd_sc_hd__xnor2_1 _213_ (
    .A(in_num3[0]),
    .B(in_num2[0]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__xor2_1 _214_ (
    .A(in_num3[0]),
    .B(in_num2[0]),
    .X(_159_)
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(in_num0[6]),
    .B(in_num2[6]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__and3_1 _216_ (
    .A(in_num0[6]),
    .B(in_num3[6]),
    .C(in_num2[6]),
    .X(_161_)
  );
  sky130_fd_sc_hd__nor2_1 _217_ (
    .A(in_num3[6]),
    .B(_160_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand3b_1 _218_ (
    .A_N(in_num0[6]),
    .B(in_num3[6]),
    .C(in_num2[6]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o21ai_0 _219_ (
    .A1(in_num3[6]),
    .A2(in_num2[6]),
    .B1(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _220_ (
    .A(in_num2[5]),
    .B(in_num0[5]),
    .Y(_165_)
  );
  sky130_fd_sc_hd__xor2_1 _221_ (
    .A(in_num3[5]),
    .B(in_num2[5]),
    .X(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _222_ (
    .A(in_num2[4]),
    .B(in_num0[4]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__xor2_1 _223_ (
    .A(in_num3[4]),
    .B(in_num2[4]),
    .X(_168_)
  );
  sky130_fd_sc_hd__a22oi_1 _224_ (
    .A1(_165_),
    .A2(_166_),
    .B1(_167_),
    .B2(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o21ai_0 _225_ (
    .A1(_162_),
    .A2(_164_),
    .B1(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__and3_1 _226_ (
    .A(in_num3[5]),
    .B(in_num2[5]),
    .C(in_num0[5]),
    .X(_000_)
  );
  sky130_fd_sc_hd__o22ai_1 _227_ (
    .A1(_162_),
    .A2(_164_),
    .B1(_169_),
    .B2(_000_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__and3_1 _228_ (
    .A(in_num3[2]),
    .B(in_num2[2]),
    .C(in_num0[2]),
    .X(_002_)
  );
  sky130_fd_sc_hd__a31oi_1 _229_ (
    .A1(in_num3[3]),
    .A2(in_num2[3]),
    .A3(in_num0[3]),
    .B1(_002_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xnor2_1 _230_ (
    .A(in_num3[2]),
    .B(in_num2[2]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a21o_1 _231_ (
    .A1(in_num2[2]),
    .A2(in_num0[2]),
    .B1(_004_),
    .X(_005_)
  );
  sky130_fd_sc_hd__xnor2_1 _232_ (
    .A(in_num3[3]),
    .B(in_num2[3]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__a21oi_1 _233_ (
    .A1(in_num2[3]),
    .A2(in_num0[3]),
    .B1(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a21o_1 _234_ (
    .A1(in_num2[3]),
    .A2(in_num0[3]),
    .B1(_006_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand3_1 _235_ (
    .A(_003_),
    .B(_005_),
    .C(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__and2_0 _236_ (
    .A(in_num2[1]),
    .B(in_num0[1]),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(in_num2[1]),
    .B(in_num0[1]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__and3_1 _238_ (
    .A(in_num3[1]),
    .B(in_num2[1]),
    .C(in_num0[1]),
    .X(_012_)
  );
  sky130_fd_sc_hd__xor2_1 _239_ (
    .A(in_num3[1]),
    .B(in_num2[1]),
    .X(_013_)
  );
  sky130_fd_sc_hd__xnor2_1 _240_ (
    .A(in_num3[1]),
    .B(in_num2[1]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__and2_0 _241_ (
    .A(in_num2[0]),
    .B(in_num0[0]),
    .X(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(in_num2[0]),
    .B(in_num0[0]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a22oi_1 _243_ (
    .A1(_011_),
    .A2(_013_),
    .B1(_016_),
    .B2(_159_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o2111ai_1 _244_ (
    .A1(_012_),
    .A2(_017_),
    .B1(_003_),
    .C1(_005_),
    .D1(_008_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a31oi_1 _245_ (
    .A1(in_num3[4]),
    .A2(in_num2[4]),
    .A3(in_num0[4]),
    .B1(_000_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o21a_1 _246_ (
    .A1(_003_),
    .A2(_007_),
    .B1(_019_),
    .X(_020_)
  );
  sky130_fd_sc_hd__a21oi_1 _247_ (
    .A1(_018_),
    .A2(_020_),
    .B1(_001_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a21oi_1 _248_ (
    .A1(in_num3[0]),
    .A2(_015_),
    .B1(_012_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand3_1 _249_ (
    .A(_017_),
    .B(_019_),
    .C(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__or3_1 _250_ (
    .A(_170_),
    .B(_009_),
    .C(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__o21ai_0 _251_ (
    .A1(_161_),
    .A2(_021_),
    .B1(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__mux2i_1 _252_ (
    .A0(_159_),
    .A1(_015_),
    .S(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o21ai_0 _253_ (
    .A1(_156_),
    .A2(_157_),
    .B1(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o211ai_1 _254_ (
    .A1(_117_),
    .A2(_148_),
    .B1(_152_),
    .C1(_128_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a211oi_1 _255_ (
    .A1(_118_),
    .A2(_149_),
    .B1(_153_),
    .C1(_128_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__mux2i_1 _256_ (
    .A0(_013_),
    .A1(_010_),
    .S(_025_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a211oi_1 _257_ (
    .A1(_130_),
    .A2(_155_),
    .B1(_029_),
    .C1(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o211ai_1 _258_ (
    .A1(_130_),
    .A2(_154_),
    .B1(_028_),
    .C1(_030_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2b_1 _259_ (
    .A(_031_),
    .B_N(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xor2_1 _260_ (
    .A(_027_),
    .B(_033_),
    .X(out_num1[0])
  );
  sky130_fd_sc_hd__a211oi_1 _261_ (
    .A1(_116_),
    .A2(_155_),
    .B1(_156_),
    .C1(_026_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xor2_1 _262_ (
    .A(_033_),
    .B(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__a21oi_1 _263_ (
    .A1(_032_),
    .A2(_034_),
    .B1(_031_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__mux2i_1 _264_ (
    .A0(_124_),
    .A1(_126_),
    .S(_155_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand3_1 _265_ (
    .A(in_num2[2]),
    .B(in_num0[2]),
    .C(_025_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o21ai_0 _266_ (
    .A1(_004_),
    .A2(_025_),
    .B1(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(_037_),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _268_ (
    .A(_037_),
    .B(_039_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_036_),
    .B(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xnor2_1 _270_ (
    .A(_035_),
    .B(_042_),
    .Y(out_num1[1])
  );
  sky130_fd_sc_hd__o21a_1 _271_ (
    .A1(_036_),
    .A2(_041_),
    .B1(_040_),
    .X(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _272_ (
    .A(_123_),
    .B(_155_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o21ai_0 _273_ (
    .A1(_122_),
    .A2(_155_),
    .B1(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand3_1 _274_ (
    .A(in_num2[3]),
    .B(in_num0[3]),
    .C(_025_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o21ai_0 _275_ (
    .A1(_006_),
    .A2(_025_),
    .B1(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__and2_0 _276_ (
    .A(_045_),
    .B(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__xnor2_1 _277_ (
    .A(_045_),
    .B(_047_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xnor2_1 _278_ (
    .A(_043_),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__xor2_1 _279_ (
    .A(_042_),
    .B(_050_),
    .X(out_num1[2])
  );
  sky130_fd_sc_hd__o21ba_1 _280_ (
    .A1(_043_),
    .A2(_049_),
    .B1_N(_048_),
    .X(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(_138_),
    .B(_155_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o31a_1 _282_ (
    .A1(in_num1[4]),
    .A2(in_num3[4]),
    .A3(_155_),
    .B1(_052_),
    .X(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _283_ (
    .A(_168_),
    .B(_025_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a21oi_1 _284_ (
    .A1(_167_),
    .A2(_025_),
    .B1(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(_053_),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__xnor2_1 _286_ (
    .A(_053_),
    .B(_055_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xnor2_1 _287_ (
    .A(_051_),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__xor2_1 _288_ (
    .A(_050_),
    .B(_058_),
    .X(out_num1[3])
  );
  sky130_fd_sc_hd__o21a_1 _289_ (
    .A1(_051_),
    .A2(_057_),
    .B1(_056_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _290_ (
    .A(_119_),
    .B(_154_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__o21ai_0 _291_ (
    .A1(_145_),
    .A2(_154_),
    .B1(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _292_ (
    .A(_166_),
    .B(_025_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a21oi_1 _293_ (
    .A1(_165_),
    .A2(_025_),
    .B1(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(_061_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__xnor2_1 _295_ (
    .A(_061_),
    .B(_063_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _296_ (
    .A(_059_),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xor2_1 _297_ (
    .A(_058_),
    .B(_066_),
    .X(out_num1[4])
  );
  sky130_fd_sc_hd__nor2_1 _298_ (
    .A(_143_),
    .B(_162_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a21oi_1 _299_ (
    .A1(in_num2[6]),
    .A2(_141_),
    .B1(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__o21a_1 _300_ (
    .A1(_059_),
    .A2(_065_),
    .B1(_064_),
    .X(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(_068_),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__xnor2_1 _302_ (
    .A(_068_),
    .B(_069_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__xor2_1 _303_ (
    .A(_066_),
    .B(_071_),
    .X(out_num1[5])
  );
  sky130_fd_sc_hd__nand2_1 _304_ (
    .A(in_num1[6]),
    .B(_162_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__o21ai_0 _305_ (
    .A1(_068_),
    .A2(_069_),
    .B1(_072_),
    .Y(out_num1[7])
  );
  sky130_fd_sc_hd__mux2_1 _306_ (
    .A0(_071_),
    .A1(_070_),
    .S(_072_),
    .X(out_num1[6])
  );
  sky130_fd_sc_hd__mux2_1 _307_ (
    .A0(_116_),
    .A1(_132_),
    .S(_155_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2i_1 _308_ (
    .A0(_016_),
    .A1(_158_),
    .S(_025_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _309_ (
    .A(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _310_ (
    .A(_073_),
    .SLEEP(_075_),
    .X(_076_)
  );
  sky130_fd_sc_hd__a211oi_1 _311_ (
    .A1(_118_),
    .A2(_149_),
    .B1(_153_),
    .C1(_130_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o211ai_1 _312_ (
    .A1(_117_),
    .A2(_148_),
    .B1(_152_),
    .C1(_130_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__mux2i_1 _313_ (
    .A0(_011_),
    .A1(_014_),
    .S(_025_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o211ai_1 _314_ (
    .A1(_128_),
    .A2(_154_),
    .B1(_078_),
    .C1(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a211oi_1 _315_ (
    .A1(_128_),
    .A2(_155_),
    .B1(_077_),
    .C1(_079_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _316_ (
    .A(_080_),
    .SLEEP(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__xnor2_1 _317_ (
    .A(_076_),
    .B(_082_),
    .Y(out_num0[1])
  );
  sky130_fd_sc_hd__o31ai_1 _318_ (
    .A1(_073_),
    .A2(_075_),
    .A3(_081_),
    .B1(_080_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _319_ (
    .A(_125_),
    .B(_155_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__o21ai_0 _320_ (
    .A1(_126_),
    .A2(_155_),
    .B1(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a21oi_1 _321_ (
    .A1(in_num2[2]),
    .A2(in_num0[2]),
    .B1(_025_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a21oi_1 _322_ (
    .A1(_004_),
    .A2(_025_),
    .B1(_086_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__xnor2_1 _323_ (
    .A(_085_),
    .B(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__xnor2_1 _324_ (
    .A(_083_),
    .B(_088_),
    .Y(out_num0[2])
  );
  sky130_fd_sc_hd__maj3_1 _325_ (
    .A(_083_),
    .B(_085_),
    .C(_087_),
    .X(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(_123_),
    .B(_154_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o21ai_0 _327_ (
    .A1(_122_),
    .A2(_154_),
    .B1(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _328_ (
    .A1(in_num2[3]),
    .A2(in_num0[3]),
    .B1(_025_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a21oi_1 _329_ (
    .A1(_006_),
    .A2(_025_),
    .B1(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(_091_),
    .B(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__xor2_1 _331_ (
    .A(_091_),
    .B(_093_),
    .X(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _332_ (
    .A(_089_),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__xor2_1 _333_ (
    .A(_089_),
    .B(_095_),
    .X(out_num0[3])
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(_094_),
    .B(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o21ai_0 _335_ (
    .A1(in_num1[4]),
    .A2(in_num3[4]),
    .B1(_155_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__o21ai_0 _336_ (
    .A1(_138_),
    .A2(_155_),
    .B1(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(_168_),
    .B(_025_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o21ai_0 _338_ (
    .A1(_167_),
    .A2(_025_),
    .B1(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _339_ (
    .A(_099_),
    .B(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__xnor2_1 _340_ (
    .A(_099_),
    .B(_101_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a21o_1 _341_ (
    .A1(_094_),
    .A2(_096_),
    .B1(_103_),
    .X(_104_)
  );
  sky130_fd_sc_hd__xnor2_1 _342_ (
    .A(_097_),
    .B(_103_),
    .Y(out_num0[4])
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(_119_),
    .B(_155_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o21ai_0 _344_ (
    .A1(_145_),
    .A2(_155_),
    .B1(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(_166_),
    .B(_025_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__o21ai_0 _346_ (
    .A1(_165_),
    .A2(_025_),
    .B1(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _347_ (
    .A(_106_),
    .B(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__xnor2_1 _348_ (
    .A(_106_),
    .B(_108_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a21o_1 _349_ (
    .A1(_102_),
    .A2(_104_),
    .B1(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nand3_1 _350_ (
    .A(_102_),
    .B(_104_),
    .C(_110_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__and2_0 _351_ (
    .A(_111_),
    .B(_112_),
    .X(out_num0[5])
  );
  sky130_fd_sc_hd__mux2i_1 _352_ (
    .A0(_164_),
    .A1(in_num2[6]),
    .S(_141_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a21o_1 _353_ (
    .A1(_109_),
    .A2(_111_),
    .B1(_113_),
    .X(_114_)
  );
  sky130_fd_sc_hd__nand3_1 _354_ (
    .A(_109_),
    .B(_111_),
    .C(_113_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__and2_0 _355_ (
    .A(_114_),
    .B(_115_),
    .X(out_num0[6])
  );
  sky130_fd_sc_hd__xnor2_1 _356_ (
    .A(_073_),
    .B(_074_),
    .Y(out_num0[0])
  );
  sky130_fd_sc_hd__o21ai_0 _357_ (
    .A1(_141_),
    .A2(_164_),
    .B1(_114_),
    .Y(out_num0[7])
  );
  assign adder_result[7] = out_num1[7];
endmodule
